config/routes.rb
Rails.application.routes.draw do

  resources :robot_instance_sessions
  resources :robot_instances
  resources :agent_sessions
  resources :agents
  #devise_for :users, :controllers => {sessions: 'sessions'} 
  devise_for :users, controllers: {
    sessions: 'sessions', 
    invitations: 'users/invitations',
    registrations: 'registrations'
    }, path_prefix: 'auth' 
  devise_scope :user do

    # API 
    namespace :api do
      namespace :v1 do
        post 'users/sign_in' => 'sessions#create'
        delete 'users/sign_out' => 'sessions#destroy'

        resources :orgs do
          get 'agents_info', on: :member
          resources :agents
        end
      end
    end

    resources :users do
      get 'my_data', on: :collection
    end

    resources :orgs do
      get 'agents_info', on: :member
    end

    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  get '/demo', to: 'home#demo'

  # http://stackoverflow.com/questions/22741975/undefined-local-variable-or-method-root-path
  root "static#home"
  
end

app/views/layouts/_admin_navigation_links.html.erb
<%# add admin navigation links to this file %>

<li><%= link_to raw(' <i class="ion-ios-people-outline"></i>Orgs'), orgs_path, id: 'admin-orgs' %></li>
<li><%= link_to raw(' <i class="ion-ios-people-outline"></i>Users'), users_path %></li>

app/views/layouts/_edit_bottom.html.erb
  </div>
</div>  

app/views/layouts/_edit_top.html.erb
<% if notice.to_s !='' %>
  <div class="alert alert-info"><%= notice %></div>
<% end %>

<div class="panel panel-piluku">
  <div class="panel-heading">
    <h1>Editing <%= item.model_name.human %> <%= item.name %>
      <span class="panel-options">
        <a href="<%= send(item.model_name.param_key + '_path', item) %>"><i class="icon ti-close"></i></a>
      </span>
    </h1>

  </div>

  <div class="panel-body">

app/views/layouts/_flash_messages.html.erb
<% # Flash error messages formatted for Bootstrap %>
<% flash.each do |key, value| %>
	<div class="<%= bootstrap_error_class(key) %>"><%= value %></div>
<% end %>

app/views/layouts/_flash_modal.html.erb
<% if flash.count > 0 %>
	<!-- Modal -->
	<div id="flashMessagesModal" class="modal fade in" role="dialog">
	  <div class="modal-dialog">

	    <!-- Modal content-->
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal">&times;</button>
	        <h4 class="modal-title">Robot Lux</h4>
	      </div>
	      <div class="modal-body">
			<% flash.each do |key, value| %>
	    		<div class="<%= bootstrap_error_class(key) %>"><%= value %></div>
			<% end %>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	      </div>
	    </div>

	  </div>
	</div>
<% end %>
<script type="text/javascript">
    $(window).load(function(){
        /**
		 * Vertically center Bootstrap 3 modals so they aren't always stuck at the top
		 */
		$(function() {
		    function reposition() {
		        var modal = $(this),
		            dialog = modal.find('.modal-dialog');
		        modal.css('display', 'block');
		        
		        // Dividing by two centers the modal exactly, but dividing by three 
		        // or four works better for larger screens.
		        dialog.css("margin-top", Math.max(0, ($(window).height() - dialog.height()) / 2));
		    }
		    // Reposition when a modal is shown
		    $('.modal').on('show.bs.modal', reposition);
		    // Reposition when the window is resized
		    $(window).on('resize', function() {
		        $('.modal:visible').each(reposition);
		    });
		});
		$('#flashMessagesModal').modal('show');
    });
</script>

app/views/layouts/_index_top.html.erb
<% if notice.to_s !='' %>
  <div class="alert alert-info"><%= notice %></div>
<% end %>

<% if defined?(index_style) %>
<%  heading_size = (index_style==:sub_table) ? 'h2' : 'h1' %>
<% else %>
<%  heading_size = 'h1' %>
<% end %>

<div class="panel panel-piluku">
  <div class="panel-heading">
    <<%= heading_size %>><%= I18n.t items_name %>
      <span class="panel-options">
        <% if defined?(new_item) %>
        <a id="new_<%= item_name %>" href="<%= send('new_' + item_name + '_path') %>"><i class="icon ti-wand"></i></a>
        <% end %>
      </span>
    </<%= heading_size %>>
  </div>

  <div class="panel-body">
    <table id="<%= items_name %>" class="table table-striped">
      <thead>
        <tr>
          <% headings.each do |heading| %>
            <th><%= heading %></th>
          <% end %>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to raw(' <i class="ion-android-create"></i>Edit profile'), edit_user_registration_path %></li>
  <li><%= link_to raw('<i class="ion-power"></i>Sign out'), destroy_user_session_path, :method=>'delete', class: 'logout_button' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_new_bottom.html.erb
  </div>
</div>  

app/views/layouts/_new_top.html.erb
<% if notice.to_s !='' %>
  <div class="alert alert-info"><%= notice %></div>
<% end %>

<div class="panel panel-piluku">
  <div class="panel-heading">
    <h1>New <%= item.model_name.human %> 
      <span class="panel-options">
        <a href="<%= send(item.model_name.route_key + '_path', item) %>"><i class="icon ti-close"></i></a>
      </span>
    </h1>

  </div>

  <div class="panel-body">

app/views/layouts/_org_menu.html.erb
<div>

	<div>
		<a href="/robot_instances"><%= I18n.t 'robot_instances' %></a>
	</div>	

</div>	

app/views/layouts/_server_connection_panel.html.erb
<div id="connection-panel">

	<div id="connection-panel-danger" class="">
		<a href="#" class="text-danger">Lost connection with the server. Will try to reconnect automatically in <span id="connection-panel-reconnect-seconds">9</span> seconds...</a>
	</div>	

	<div id="connection-panel-warning" class="">
		<a href="#" class="text-warning">Connecting...</a>
	</div>	

	<div id="connection-panel-success">
		<a href="#" class="text-success">Connected OK to server.</a>
	</div>	

</div>	

app/views/layouts/_show_field.html.erb
        <tr>
          <td><%= field_name %></td>
          <td>
            <a href="#" id="<%= field_id %>" data-type="text" data-pk="1" data-title="Enter <%= field_name %>" class="editable editable-click"><%= field_value %>
          </td>
        </tr>

app/views/layouts/lock_screen.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">	
	<title>RobotLux | Sign In</title>
	<!-- <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
	<link rel="icon" href="images/favicon.ico" type="image/x-icon"> -->
	<!-- Bootstrap CSS -->

	<!-- custom scrollbar stylesheet -->	
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/> <!--320-->
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

	<!-- Bootstrap files -->
	<!-- Optional theme -->

<!--
	<link rel="stylesheet" type="text/css" href="/assets/piluku/lock-screen2.css">	
-->	
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>
<body>
	
	<div class="flip-container">
		<div class="flipper">
			<div class="front">
				<!-- front content -->
				<div class="holder">
					<h1 class="heading">robot lux</h1>	
					<p><%= t('login.welcome') %></p>	

					<%= yield %>

				</div>
			</div>
			<div class="back">
				<!-- front content -->				
				<div class="holder">
					<div class="avatar_holder">
						<img src="/assets/piluku/avatar/five.png" alt="">
					</div>						
					<div class="log_msg"><%= t('login.logging_in') %></div>					
				</div>
			</div>
		</div>
		<div class="load_pulse"></div>
	</div>

	<!-- Modal -->
	<div class="modal fade" id="forgot" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="myModalLabel"><i class="ion-android-settings"></i> Reset password</h4>
				</div>
				<div class="modal-body">
					<div class="col-sm-12">
						<input type="text" class="form-control" placeholder="Enter Email here">
						<h6 class="note"><i class="ion-android-mail"></i> password will be sent to your email</h6>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-red" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-primary">Send</button>
				</div>
			</div>
		</div>
	</div>
	<!-- modal -->
	<script src="/assets/piluku/lockscreen.js"></script>	


</body>
</html>